version: '3'

services:    
  mysqldb:
    build: 
      context: ./MySql
      dockerfile: Dockerfile
    image: mysqldb
    networks:
      - bi-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=JQTJ7Y
    ports:
      - '3307:3306'  

  bi-nifi:
    build:
      context: ./Nifi
      dockerfile: Dockerfile
    image: bi-nifi
    volumes: 
      - ./Nifi/files:/files/
    ports:
      - '9090:9090'
    networks:
      - bi-network
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    depends_on:
      - mysqldb
    
networks:
  bi-network: